### ISSUE TITLE
pod install 报错

### ISSUE THREAD

**Issue by zczb** [wwmz/WMZDropDownMenu#42]
报错信息CocoaPods could not find compatible versions for pod "WMZDropDownMenu":
  In Podfile:
    WMZDropDownMenu (~> 1.2.0)
None of your spec sources contain a spec satisfying the dependency: `WMZDropDownMenu (~> 1.2.0)`.

**Comment by wwmz** [comment]
你更新一下本地cocopod吧 已经发布的了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zczb ***@***.***&gt;
发送时间: 2021年11月1日 11:37
收件人: wwmz/WMZDropDownMenu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[wwmz/WMZDropDownMenu] pod install 报错 (Issue #42)





 
报错信息CocoaPods could not find compatible versions for pod "WMZDropDownMenu":
 In Podfile:
 WMZDropDownMenu (~&gt; 1.2.0)
 None of your spec sources contain a spec satisfying the dependency: WMZDropDownMenu (~&gt; 1.2.0).
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
